# Generated by Django 3.0.8 on 2020-07-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenoms', models.CharField(max_length=50)),
                ('adresse', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], default='Interne', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id_droit', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('droit_adhension', models.BooleanField(default=False, help_text='Payé?', verbose_name="Droit d'adhension")),
                ('droit_annuel', models.BooleanField(default=False, help_text='Payé?', verbose_name='Droit Annuel')),
                ('droit_reception', models.BooleanField(default=False, help_text='Payé?', verbose_name='Droit de réception')),
                ('id_membres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Membres')),
            ],
        ),
    ]
